production:
  databases:
    default:
      adapter: postgres
      encoding: unicode
      database: ginga
      username: postgres
      password: afro112358
      host: 127.0.0.1
  options:
    separator: ;

development:
  databases:
    default:
      adapter: postgres
      encoding: unicode
      database: ginga_dev
      username: postgres
      password: mosespass
      host: 127.0.0.1
  options:
    separator: ;

